[colors.primary]
background = "0x010101"
foreground = "0xf8f8f6"

[colors.normal]
black = "0x242424"
red = "0xff8989"
green = "0xffbf73"
yellow = "0xfcff84"
magenta = "0xf463e8"
blue = "0x81c8f4"
cyan = "0x88d8f1"
white = "0xfefefe"

[colors.bright]
black = "0x323232"
red = "0xffadad"
green = "0xffd6a5"
yellow = "0xfdffb6"
magenta = "0xf485eb"
blue = "0x98d1f4"
cyan = "0xaee1f1"
white = "0xffffff"
